env:
  global:
    - CC_TEST_REPORTER_ID=244bf80f943e25a4869ff0f698f01cbefc74951481ffd3745c81393f4544f8a9
language: php
php:
  - 7.3
  - 7.2
  - 7.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - composer self-update
  - composer install --dev
script:
  - vendor/bin/robo test:coverage-codeclimate
after_script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

